# Generated by Django 6.0.2 on 2026-03-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
